# Generated by Django 5.1.7 on 2025-03-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specification')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventory')),
                ('specification_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.specificationvalue')),
            ],
        ),
    ]
