# Generated by Django 5.1.7 on 2025-03-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_specification_specificationvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product_inventory',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='inventory.product'),
        ),
    ]
