# Generated by Django 5.1.7 on 2025-03-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_productspecification_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationvalue',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.specification'),
        ),
    ]
