# Generated by Django 5.1.7 on 2025-03-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_specificationvalue_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='inventory.specificationgroup'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specificationgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('group', 'key')},
        ),
    ]
