# Generated by Django 5.1.7 on 2025-03-22 03:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_productinventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
