# Generated by Django 5.1.7 on 2025-03-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_productinventory_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
